#!/usr/bin/env bash
# Behaviour tests for scripts/post-commit.sh.
#
# Every case builds a REAL throwaway git repo and runs the gate over a real
# head/range — never a mocked `git log`. The bugs this gate exists to catch
# (case-sensitive trailers, author-identity attribution, history reachability)
# are all bugs in how git actually formats and links things; a mock would
# have happily passed them.
set -uo pipefail
ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
GATE="$ROOT/scripts/post-commit.sh"
PASS=0; FAIL=0
RANGE_SPEC='HEAD~1..HEAD'   # per-case override, reset after each check

mkrepo() {
    local d; d="$(mktemp -d)"
    git -C "$d" init -q -b main
    git -C "$d" config user.email dev@example.com
    git -C "$d" config user.name "Dev"
    git -C "$d" config commit.gpgsign false
    git -C "$d" config core.hooksPath /dev/null   # immune to the host's global hooks
    echo seed > "$d/seed.txt"
    git -C "$d" add -A
    git -C "$d" commit -qm "chore: seed"
    printf '%s' "$d"
}

# check <name> <expected-exit> <repo> [VAR=value ...]
check() {
    local name="$1" want="$2" repo="$3"; shift 3
    local out rc
    out="$(cd "$repo" && env GITHUB_STEP_SUMMARY=/dev/null "$@" bash "$GATE" HEAD "$RANGE_SPEC" 2>&1)"
    rc=$?
    if [ "$rc" -eq "$want" ]; then
        PASS=$((PASS+1)); printf '  ok   %s\n' "$name"
    else
        FAIL=$((FAIL+1)); printf '  FAIL %s (want exit %s, got %s)\n%s\n' "$name" "$want" "$rc" "$(printf '%s' "$out" | sed 's/^/       /')"
    fi
    rm -rf "$repo"
    RANGE_SPEC='HEAD~1..HEAD'
}

commit_msg() {  # commit_msg <repo> <message>
    local d="$1"; shift
    echo "$RANDOM$RANDOM" > "$d/f.txt"
    git -C "$d" add -A
    git -C "$d" commit -q -F - <<< "$1"
}

echo "== clean (expect 0) =="
d=$(mkrepo); commit_msg "$d" "feat(api): add pagination to /users"
check "conventional commit, clean history" 0 "$d"

d=$(mkrepo); commit_msg "$d" "docs: update claude code settings in devcontainer"
check "'claude code' as subject matter is allowed by default" 0 "$d"

d=$(mkrepo); commit_msg "$d" "chore: regenerate stubs generated by protoc"
check "'generated by protoc' is not an AI banner" 0 "$d"

d=$(mkrepo); commit_msg "$d" "fix: handle .claude/ path lookups"
check "'.claude/' allowed by default (strict-only)" 0 "$d"

d=$(mkrepo); commit_msg "$d" "feat(api)!: drop v1 endpoints"
check "breaking-change marker" 0 "$d"

d=$(mkrepo); commit_msg "$d" 'Revert "feat: thing"'
check "git-native revert subject" 0 "$d"

d=$(mkrepo)
git -C "$d" checkout -q -b topic; commit_msg "$d" "feat: on topic"
git -C "$d" checkout -q main; echo m > "$d/m.txt"; git -C "$d" add -A; git -C "$d" commit -qm "chore: on main"
BASE=$(git -C "$d" rev-parse HEAD)
git -C "$d" merge -q --no-ff topic -m "Merge branch 'topic'"
RANGE_SPEC="$BASE..HEAD"
check "merge commit subject is skipped by the format check" 0 "$d"

d=$(mkrepo)
echo 'AKIA0000000000000000' > "$d/old.txt"; git -C "$d" add -A; git -C "$d" commit -qm "chore: preexisting"
git -C "$d" rm -q old.txt; git -C "$d" commit -qm "fix: remove leaked key"
check "removing a secret does not fail the change that removes it" 0 "$d"

echo "== AI attribution (expect 1) =="
d=$(mkrepo); commit_msg "$d" "feat: thing

Co-authored-by: Claude <noreply@anthropic.com>"
check "git-default lowercase 'Co-authored-by:' (the #447 regression)" 1 "$d"

d=$(mkrepo); commit_msg "$d" "feat: thing

Co-Authored-By: Claude Opus <noreply@anthropic.com>"
check "title-case trailer" 1 "$d"

d=$(mkrepo); commit_msg "$d" "feat: thing

CO-AUTHORED-BY: CLAUDE <X@Y>"
check "all-caps trailer" 1 "$d"

d=$(mkrepo); commit_msg "$d" "feat: thing

🤖 Generated with [Claude Code](https://claude.com/claude-code)"
check "robot-emoji footer" 1 "$d"

d=$(mkrepo); commit_msg "$d" "feat: thing

Generated with Claude"
check "'Generated with Claude' banner without emoji" 1 "$d"

d=$(mkrepo); commit_msg "$d" "feat: thing (AI-assisted)"
check "'AI-assisted'" 1 "$d"

d=$(mkrepo); commit_msg "$d" "feat: thing

Assisted-by: GitHub Copilot"
check "'Assisted-by:' trailer" 1 "$d"

d=$(mkrepo); commit_msg "$d" "feat: thing

Plan: .claude/plans/thing.md"
check "'Plan:' footer leak (#364)" 1 "$d"

d=$(mkrepo)
echo x > "$d/f.txt"; git -C "$d" add -A
git -C "$d" -c user.name="Claude" -c user.email="noreply@anthropic.com" commit -qm "feat: perfectly clean message"
check "clean message but AI author identity" 1 "$d"

d=$(mkrepo)
echo x > "$d/f.txt"; git -C "$d" add -A
GIT_COMMITTER_NAME="Claude" GIT_COMMITTER_EMAIL="noreply@anthropic.com" git -C "$d" commit -qm "feat: clean message, AI committer"
check "clean message but AI committer identity" 1 "$d"

echo "== history reachability =="
d=$(mkrepo)
commit_msg "$d" "feat: old tainted work

Co-authored-by: Claude <noreply@anthropic.com>"
commit_msg "$d" "feat: brand new clean commit"
check "tainted ancestor fails a clean commit (full history, default)" 1 "$d"

d=$(mkrepo)
commit_msg "$d" "feat: old tainted work

Co-authored-by: Claude <noreply@anthropic.com>"
commit_msg "$d" "feat: brand new clean commit"
check "same repo passes in range mode" 0 "$d" PC_HISTORY=range

echo "== strict =="
d=$(mkrepo); commit_msg "$d" "docs: update claude code settings"
check "'claude code' fails under strict" 1 "$d" PC_STRICT=true

d=$(mkrepo); commit_msg "$d" "fix: handle .claude/ lookups"
check "'.claude/' fails under strict" 1 "$d" PC_STRICT=true

echo "== identity =="
# The allowlist is opt-in: an empty PC_AUTHORS must not fail a repo that
# never asked for the rule (every case above runs with dev@example.com).
d=$(mkrepo); commit_msg "$d" "feat: thing"
check "no PC_AUTHORS — identity check is off" 0 "$d"

d=$(mkrepo)
git -C "$d" config user.email "133899878+kodflow@users.noreply.github.com"
git -C "$d" config user.name "Kodflow"
commit_msg "$d" "feat: thing"
check "allowed login with id prefix" 0 "$d" PC_AUTHORS=kodflow PC_HISTORY=range

d=$(mkrepo)
git -C "$d" config user.email "kodflow@users.noreply.github.com"
commit_msg "$d" "feat: thing"
check "allowed login without id prefix" 0 "$d" PC_AUTHORS=kodflow PC_HISTORY=range

d=$(mkrepo)
git -C "$d" config user.email "florent@making.codes"
git -C "$d" config user.name "Florent"
commit_msg "$d" "feat: thing"
check "personal identity is refused" 1 "$d" PC_AUTHORS=kodflow PC_HISTORY=range

d=$(mkrepo)
git -C "$d" config user.email "someone-else@users.noreply.github.com"
commit_msg "$d" "feat: thing"
check "another GitHub account is refused" 1 "$d" PC_AUTHORS=kodflow PC_HISTORY=range

# A clean author with a foreign committer still fails: rewriting only the
# author half is exactly how a bad identity survives a sloppy fixup.
d=$(mkrepo)
git -C "$d" config user.email "133899878+kodflow@users.noreply.github.com"
echo x > "$d/f.txt"; git -C "$d" add -A
GIT_COMMITTER_NAME="Florent" GIT_COMMITTER_EMAIL="florent@making.codes" \
    git -C "$d" commit -qm "feat: thing"
check "foreign committer is refused even with an allowed author" 1 "$d" PC_AUTHORS=kodflow PC_HISTORY=range

d=$(mkrepo)
git -C "$d" config user.email "49699333+dependabot[bot]@users.noreply.github.com"
git -C "$d" config user.name "dependabot[bot]"
commit_msg "$d" "chore: bump actions/checkout"
check "bot accounts are always allowed" 0 "$d" PC_AUTHORS=kodflow PC_HISTORY=range

d=$(mkrepo)
git -C "$d" config user.email "noreply@github.com"
git -C "$d" config user.name "GitHub"
commit_msg "$d" "feat: merged through the web UI"
check "GitHub's own merge committer is allowed" 0 "$d" PC_AUTHORS=kodflow PC_HISTORY=range

d=$(mkrepo)
git -C "$d" config user.email "second@users.noreply.github.com"
commit_msg "$d" "feat: thing"
check "several logins in the list" 0 "$d" PC_AUTHORS="kodflow,second" PC_HISTORY=range

# full history is the fleet default: one foreign ancestor blocks a clean tip.
d=$(mkrepo)
git -C "$d" config user.email "florent@making.codes"
commit_msg "$d" "feat: tainted ancestor"
git -C "$d" config user.email "133899878+kodflow@users.noreply.github.com"
commit_msg "$d" "feat: clean tip"
check "foreign ancestor blocks a clean tip in full mode" 1 "$d" PC_AUTHORS=kodflow

echo "== format (expect 1) =="
d=$(mkrepo); commit_msg "$d" "Update README.md"
check "GitHub web-UI default subject" 1 "$d"

d=$(mkrepo); commit_msg "$d" "feat:missing space"
check "missing space after colon" 1 "$d"

d=$(mkrepo); commit_msg "$d" "feature: unknown type"
check "unknown type" 1 "$d"

d=$(mkrepo); commit_msg "$d" "Update README.md"
check "format check disabled" 0 "$d" PC_FORMAT=false

echo "== secrets (expect 1) =="
d=$(mkrepo); echo 'AKIAIOSFODNN7EXAMPLE' > "$d/f.txt"; git -C "$d" add -A; git -C "$d" commit -qm "chore: config"
check "AWS access key id" 1 "$d"

d=$(mkrepo); echo 'password = "hunter2000"' > "$d/f.txt"; git -C "$d" add -A; git -C "$d" commit -qm "chore: config"
check "hardcoded password assignment" 1 "$d"

d=$(mkrepo); echo 'password: "hunter2000"' > "$d/f.yml"; git -C "$d" add -A; git -C "$d" commit -qm "chore: config"
check "hardcoded password in YAML" 1 "$d"

d=$(mkrepo); echo '-----BEGIN RSA PRIVATE KEY-----' > "$d/f.txt"; git -C "$d" add -A; git -C "$d" commit -qm "chore: key"
check "private key header" 1 "$d"

d=$(mkrepo); echo 'ghp_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' > "$d/f.txt"; git -C "$d" add -A; git -C "$d" commit -qm "chore: token"
check "github PAT" 1 "$d"

d=$(mkrepo); echo 'AKIAIOSFODNN7EXAMPLE' > "$d/f.txt"; git -C "$d" add -A; git -C "$d" commit -qm "chore: config"
check "secret scan disabled" 0 "$d" PC_SECRETS=false

d=$(mkrepo); mkdir -p "$d/tests" "$d/pkg/testdata"
echo 'AKIAIOSFODNN7EXAMPLE' > "$d/tests/fixture.txt"; echo 'ghp_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' > "$d/pkg/testdata/token.txt"
echo 'password = "hunter2000"' > "$d/scanner_test.go"
git -C "$d" add -A; git -C "$d" commit -qm "test: scanner fixtures"
check "fake credentials under test/fixture paths are excluded" 0 "$d"

d=$(mkrepo); mkdir -p "$d/tests"; echo 'AKIAIOSFODNN7EXAMPLE' > "$d/tests/fixture.txt"; echo 'AKIAIOSFODNN7EXAMPLE' > "$d/config.txt"
git -C "$d" add -A; git -C "$d" commit -qm "chore: config"
check "a real path still fails even with a fixture alongside" 1 "$d"

echo "== usage errors (expect 2) =="
d=$(mkrepo)
out="$(cd "$d" && bash "$GATE" 2>&1)"; rc=$?
if [ "$rc" -eq 2 ]; then PASS=$((PASS+1)); echo "  ok   no head-rev is a usage error"; else FAIL=$((FAIL+1)); echo "  FAIL usage (got $rc)"; fi
rm -rf "$d"

echo ""
echo "passed: $PASS  failed: $FAIL"
[ "$FAIL" -eq 0 ]
