#!/usr/bin/env bash
# Behaviour tests for scripts/post-commit.sh.
#
# Every case builds a REAL throwaway git repo and runs the gate over a real
# head/range — never a mocked `git log`. The bugs this gate exists to catch
# (case-sensitive trailers, author-identity attribution, history reachability)
# are all bugs in how git actually formats and links things; a mock would
# have happily passed them.
set -uo pipefail
ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
GATE="$ROOT/scripts/post-commit.sh"
PASS=0; FAIL=0
RANGE_SPEC='HEAD~1..HEAD'   # per-case override, reset after each check

mkrepo() {
    local d; d="$(mktemp -d)"
    git -C "$d" init -q -b main
    git -C "$d" config user.email dev@example.com
    git -C "$d" config user.name "Dev"
    git -C "$d" config commit.gpgsign false
    git -C "$d" config core.hooksPath /dev/null   # immune to the host's global hooks
    # …and to its global gitignore. This machine's carries
    # `**/.claude/settings.local.json`, so three cases silently tested nothing:
    # the file was created, never tracked, and the gate correctly found an empty
    # tree. A test repo must be built from what the case writes, not from what
    # the developer running it happens to exclude.
    git -C "$d" config core.excludesFile /dev/null
    echo seed > "$d/seed.txt"
    git -C "$d" add -A
    git -C "$d" commit -qm "chore: seed"
    printf '%s' "$d"
}

# check <name> <expected-exit> <repo> [VAR=value ...]
check() {
    local name="$1" want="$2" repo="$3"; shift 3
    local out rc
    out="$(cd "$repo" && env GITHUB_STEP_SUMMARY=/dev/null "$@" bash "$GATE" HEAD "$RANGE_SPEC" 2>&1)"
    rc=$?
    if [ "$rc" -eq "$want" ]; then
        PASS=$((PASS+1)); printf '  ok   %s\n' "$name"
    else
        FAIL=$((FAIL+1)); printf '  FAIL %s (want exit %s, got %s)\n%s\n' "$name" "$want" "$rc" "$(printf '%s' "$out" | sed 's/^/       /')"
    fi
    rm -rf "$repo"
    RANGE_SPEC='HEAD~1..HEAD'
}

commit_msg() {  # commit_msg <repo> <message>
    local d="$1"; shift
    echo "$RANDOM$RANDOM" > "$d/f.txt"
    git -C "$d" add -A
    git -C "$d" commit -q -F - <<< "$1"
}

echo "== clean (expect 0) =="
d=$(mkrepo); commit_msg "$d" "feat(api): add pagination to /users"
check "conventional commit, clean history" 0 "$d"

d=$(mkrepo); commit_msg "$d" "docs: update claude code settings in devcontainer"
check "'claude code' as subject matter is allowed by default" 0 "$d"

d=$(mkrepo); commit_msg "$d" "chore: regenerate stubs generated by protoc"
check "'generated by protoc' is not an AI banner" 0 "$d"

d=$(mkrepo); commit_msg "$d" "fix: handle .claude/ path lookups"
check "'.claude/' allowed by default (strict-only)" 0 "$d"

d=$(mkrepo); commit_msg "$d" "feat(api)!: drop v1 endpoints"
check "breaking-change marker" 0 "$d"

d=$(mkrepo); commit_msg "$d" 'Revert "feat: thing"'
check "git-native revert subject" 0 "$d"

d=$(mkrepo)
git -C "$d" checkout -q -b topic; commit_msg "$d" "feat: on topic"
git -C "$d" checkout -q main; echo m > "$d/m.txt"; git -C "$d" add -A; git -C "$d" commit -qm "chore: on main"
BASE=$(git -C "$d" rev-parse HEAD)
git -C "$d" merge -q --no-ff topic -m "Merge branch 'topic'"
RANGE_SPEC="$BASE..HEAD"
check "merge commit subject is skipped by the format check" 0 "$d"

d=$(mkrepo)
echo 'AKIA0000000000000000' > "$d/old.txt"; git -C "$d" add -A; git -C "$d" commit -qm "chore: preexisting"
git -C "$d" rm -q old.txt; git -C "$d" commit -qm "fix: remove leaked key"
check "removing a secret does not fail the change that removes it" 0 "$d"

echo "== AI attribution (expect 1) =="
d=$(mkrepo); commit_msg "$d" "feat: thing

Co-authored-by: Claude <noreply@anthropic.com>"
check "git-default lowercase 'Co-authored-by:' (the #447 regression)" 1 "$d"

d=$(mkrepo); commit_msg "$d" "feat: thing

Co-Authored-By: Claude Opus <noreply@anthropic.com>"
check "title-case trailer" 1 "$d"

d=$(mkrepo); commit_msg "$d" "feat: thing

CO-AUTHORED-BY: CLAUDE <X@Y>"
check "all-caps trailer" 1 "$d"

d=$(mkrepo); commit_msg "$d" "feat: thing

🤖 Generated with [Claude Code](https://claude.com/claude-code)"
check "robot-emoji footer" 1 "$d"

d=$(mkrepo); commit_msg "$d" "feat: thing

Generated with Claude"
check "'Generated with Claude' banner without emoji" 1 "$d"

d=$(mkrepo); commit_msg "$d" "feat: thing (AI-assisted)"
check "'AI-assisted'" 1 "$d"

d=$(mkrepo); commit_msg "$d" "feat: thing

Assisted-by: GitHub Copilot"
check "'Assisted-by:' trailer" 1 "$d"

d=$(mkrepo); commit_msg "$d" "feat: thing

Plan: .claude/plans/thing.md"
check "'Plan:' footer leak (#364)" 1 "$d"

d=$(mkrepo)
echo x > "$d/f.txt"; git -C "$d" add -A
git -C "$d" -c user.name="Claude" -c user.email="noreply@anthropic.com" commit -qm "feat: perfectly clean message"
check "clean message but AI author identity" 1 "$d"

d=$(mkrepo)
echo x > "$d/f.txt"; git -C "$d" add -A
GIT_COMMITTER_NAME="Claude" GIT_COMMITTER_EMAIL="noreply@anthropic.com" git -C "$d" commit -qm "feat: clean message, AI committer"
check "clean message but AI committer identity" 1 "$d"

echo "== history reachability =="
d=$(mkrepo)
commit_msg "$d" "feat: old tainted work

Co-authored-by: Claude <noreply@anthropic.com>"
commit_msg "$d" "feat: brand new clean commit"
check "tainted ancestor fails a clean commit (full history, default)" 1 "$d"

d=$(mkrepo)
commit_msg "$d" "feat: old tainted work

Co-authored-by: Claude <noreply@anthropic.com>"
commit_msg "$d" "feat: brand new clean commit"
check "same repo passes in range mode" 0 "$d" PC_HISTORY=range

echo "== strict =="
d=$(mkrepo); commit_msg "$d" "docs: update claude code settings"
check "'claude code' fails under strict" 1 "$d" PC_STRICT=true

d=$(mkrepo); commit_msg "$d" "fix: handle .claude/ lookups"
check "'.claude/' fails under strict" 1 "$d" PC_STRICT=true

echo "== identity =="
# The allowlist is opt-in: an empty PC_AUTHORS must not fail a repo that
# never asked for the rule (every case above runs with dev@example.com).
d=$(mkrepo); commit_msg "$d" "feat: thing"
check "no PC_AUTHORS — identity check is off" 0 "$d"

d=$(mkrepo)
git -C "$d" config user.email "133899878+kodflow@users.noreply.github.com"
git -C "$d" config user.name "Kodflow"
commit_msg "$d" "feat: thing"
check "allowed login with id prefix" 0 "$d" PC_AUTHORS=kodflow PC_HISTORY=range

d=$(mkrepo)
git -C "$d" config user.email "kodflow@users.noreply.github.com"
commit_msg "$d" "feat: thing"
check "allowed login without id prefix" 0 "$d" PC_AUTHORS=kodflow PC_HISTORY=range

d=$(mkrepo)
git -C "$d" config user.email "florent@making.codes"
git -C "$d" config user.name "Florent"
commit_msg "$d" "feat: thing"
check "personal identity is refused" 1 "$d" PC_AUTHORS=kodflow PC_HISTORY=range

d=$(mkrepo)
git -C "$d" config user.email "someone-else@users.noreply.github.com"
commit_msg "$d" "feat: thing"
check "another GitHub account is refused" 1 "$d" PC_AUTHORS=kodflow PC_HISTORY=range

# A clean author with a foreign committer still fails: rewriting only the
# author half is exactly how a bad identity survives a sloppy fixup.
d=$(mkrepo)
git -C "$d" config user.email "133899878+kodflow@users.noreply.github.com"
echo x > "$d/f.txt"; git -C "$d" add -A
GIT_COMMITTER_NAME="Florent" GIT_COMMITTER_EMAIL="florent@making.codes" \
    git -C "$d" commit -qm "feat: thing"
check "foreign committer is refused even with an allowed author" 1 "$d" PC_AUTHORS=kodflow PC_HISTORY=range

d=$(mkrepo)
git -C "$d" config user.email "49699333+dependabot[bot]@users.noreply.github.com"
git -C "$d" config user.name "dependabot[bot]"
commit_msg "$d" "chore: bump actions/checkout"
check "bot accounts are always allowed" 0 "$d" PC_AUTHORS=kodflow PC_HISTORY=range

d=$(mkrepo)
git -C "$d" config user.email "noreply@github.com"
git -C "$d" config user.name "GitHub"
commit_msg "$d" "feat: merged through the web UI"
check "GitHub's own merge committer is allowed" 0 "$d" PC_AUTHORS=kodflow PC_HISTORY=range

d=$(mkrepo)
git -C "$d" config user.email "second@users.noreply.github.com"
commit_msg "$d" "feat: thing"
check "several logins in the list" 0 "$d" PC_AUTHORS="kodflow,second" PC_HISTORY=range

# full history is the fleet default: one foreign ancestor blocks a clean tip.
d=$(mkrepo)
git -C "$d" config user.email "florent@making.codes"
commit_msg "$d" "feat: tainted ancestor"
git -C "$d" config user.email "133899878+kodflow@users.noreply.github.com"
commit_msg "$d" "feat: clean tip"
check "foreign ancestor blocks a clean tip in full mode" 1 "$d" PC_AUTHORS=kodflow

# An identity trailer carries an address as durably as the author field. These
# name a human, not an assistant, so the AI-attribution patterns never see them.
d=$(mkrepo)
git -C "$d" config user.email "133899878+kodflow@users.noreply.github.com"
commit_msg "$d" "feat: thing

Co-authored-by: Florent <florent.hagard@example.com>"
check "personal address in a Co-authored-by is refused" 1 "$d" PC_AUTHORS=kodflow PC_HISTORY=range

d=$(mkrepo)
git -C "$d" config user.email "133899878+kodflow@users.noreply.github.com"
commit_msg "$d" "feat: thing

Signed-off-by: kodflow <music.music59@example.com>"
check "personal address in a Signed-off-by is refused" 1 "$d" PC_AUTHORS=kodflow PC_HISTORY=range

d=$(mkrepo)
git -C "$d" config user.email "133899878+kodflow@users.noreply.github.com"
commit_msg "$d" "feat: thing

Co-authored-by: Kodflow <133899878+kodflow@users.noreply.github.com>"
check "an allowed account in a trailer is fine" 0 "$d" PC_AUTHORS=kodflow PC_HISTORY=range

# dependabot signs off as <support@github.com>, which no allow-list of human
# logins can express — the [bot] suffix on the name is what clears it.
d=$(mkrepo)
git -C "$d" config user.email "133899878+kodflow@users.noreply.github.com"
commit_msg "$d" "chore: bump something

Signed-off-by: dependabot[bot] <support@github.com>"
check "a [bot] trailer is allowed whatever its address" 0 "$d" PC_AUTHORS=kodflow PC_HISTORY=range

d=$(mkrepo)
git -C "$d" config user.email "133899878+kodflow@users.noreply.github.com"
commit_msg "$d" "feat: thing

Co-authored-by: Someone <someone@example.com>"
check "the trailer check is off when no authors are declared" 0 "$d" PC_HISTORY=range

# A tag can hold commits no branch reaches. --branches alone called that clean.
d=$(mkrepo)
git -C "$d" config user.email "133899878+kodflow@users.noreply.github.com"
commit_msg "$d" "feat: clean base"
git -C "$d" checkout -q -b side
git -C "$d" config user.email "florent@making.codes"
commit_msg "$d" "feat: tainted"
git -C "$d" tag archived
git -C "$d" checkout -q -
git -C "$d" branch -qD side
out="$(cd "$d" && env GITHUB_STEP_SUMMARY=/dev/null PC_AUTHORS=kodflow bash "$GATE" --branches 2>&1)"; rc=$?
if [ "$rc" -eq 1 ]; then PASS=$((PASS+1)); printf '  ok   %s\n' "a commit only a tag reaches is still scanned"
else FAIL=$((FAIL+1)); printf '  FAIL %s (want exit 1, got %s)\n' "a commit only a tag reaches is still scanned" "$rc"; fi

echo "== report sink =="
# PC_REPORT is what puts the verdict in a pull-request comment. A caller reads
# the file back, so an empty or missing one silently degrades the comment to
# "no report" — worth a test rather than a hope.
d=$(mkrepo); commit_msg "$d" "feat: clean"
r="$(mktemp)"
( cd "$d" && env GITHUB_STEP_SUMMARY=/dev/null PC_REPORT="$r" bash "$GATE" HEAD HEAD~1..HEAD ) >/dev/null 2>&1
if grep -q '## post-commit' "$r" && grep -q 'Clean' "$r"; then
    PASS=$((PASS+1)); printf '  ok   %s\n' "PC_REPORT holds the verdict of a clean run"
else
    FAIL=$((FAIL+1)); printf '  FAIL %s\n' "PC_REPORT holds the verdict of a clean run"
fi
rm -rf "$d" "$r"

d=$(mkrepo); commit_msg "$d" "feat: thing

Co-authored-by: Claude <noreply@anthropic.com>"
r="$(mktemp)"
( cd "$d" && env GITHUB_STEP_SUMMARY=/dev/null PC_REPORT="$r" bash "$GATE" HEAD HEAD~1..HEAD ) >/dev/null 2>&1
if grep -q 'AI attribution' "$r"; then
    PASS=$((PASS+1)); printf '  ok   %s\n' "PC_REPORT names the violation on a failing run"
else
    FAIL=$((FAIL+1)); printf '  FAIL %s\n' "PC_REPORT names the violation on a failing run"
fi
rm -rf "$d" "$r"

d=$(mkrepo); commit_msg "$d" "feat: clean"
( cd "$d" && env GITHUB_STEP_SUMMARY=/dev/null bash "$GATE" HEAD HEAD~1..HEAD ) >/dev/null 2>&1
rc=$?
if [ "$rc" -eq 0 ]; then
    PASS=$((PASS+1)); printf '  ok   %s\n' "no PC_REPORT is not an error"
else
    FAIL=$((FAIL+1)); printf '  FAIL %s (exit %s)\n' "no PC_REPORT is not an error" "$rc"
fi
rm -rf "$d"

echo "== format (expect 1) =="
d=$(mkrepo); commit_msg "$d" "Update README.md"
check "GitHub web-UI default subject" 1 "$d"

d=$(mkrepo); commit_msg "$d" "feat:missing space"
check "missing space after colon" 1 "$d"

d=$(mkrepo); commit_msg "$d" "feature: unknown type"
check "unknown type" 1 "$d"

d=$(mkrepo); commit_msg "$d" "Update README.md"
check "format check disabled" 0 "$d" PC_FORMAT=false

echo "== secrets (expect 1) =="
d=$(mkrepo); echo 'AKIAIOSFODNN7EXAMPLE' > "$d/f.txt"; git -C "$d" add -A; git -C "$d" commit -qm "chore: config"
check "AWS access key id" 1 "$d"

d=$(mkrepo); echo 'password = "hunter2000"' > "$d/f.txt"; git -C "$d" add -A; git -C "$d" commit -qm "chore: config"
check "hardcoded password assignment" 1 "$d"

d=$(mkrepo); echo 'password: "hunter2000"' > "$d/f.yml"; git -C "$d" add -A; git -C "$d" commit -qm "chore: config"
check "hardcoded password in YAML" 1 "$d"

d=$(mkrepo); echo '-----BEGIN RSA PRIVATE KEY-----' > "$d/f.txt"; git -C "$d" add -A; git -C "$d" commit -qm "chore: key"
check "private key header" 1 "$d"

d=$(mkrepo); echo 'ghp_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' > "$d/f.txt"; git -C "$d" add -A; git -C "$d" commit -qm "chore: token"
check "github PAT" 1 "$d"

d=$(mkrepo); echo 'AKIAIOSFODNN7EXAMPLE' > "$d/f.txt"; git -C "$d" add -A; git -C "$d" commit -qm "chore: config"
check "secret scan disabled" 0 "$d" PC_SECRETS=false

d=$(mkrepo); mkdir -p "$d/tests" "$d/pkg/testdata"
echo 'AKIAIOSFODNN7EXAMPLE' > "$d/tests/fixture.txt"; echo 'ghp_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' > "$d/pkg/testdata/token.txt"
echo 'password = "hunter2000"' > "$d/scanner_test.go"
git -C "$d" add -A; git -C "$d" commit -qm "test: scanner fixtures"
check "fake credentials under test/fixture paths are excluded" 0 "$d"

d=$(mkrepo); mkdir -p "$d/tests"; echo 'AKIAIOSFODNN7EXAMPLE' > "$d/tests/fixture.txt"; echo 'AKIAIOSFODNN7EXAMPLE' > "$d/config.txt"
git -C "$d" add -A; git -C "$d" commit -qm "chore: config"
check "a real path still fails even with a fixture alongside" 1 "$d"

echo "== agent artefacts: configuration is source, exhaust is not =="
# The rule refuses what an agent WRITES, not what a human wrote for it. These
# first cases are the ones a repository is entitled to carry.
d=$(mkrepo); mkdir -p "$d/.claude/agents" "$d/.claude/commands" "$d/.claude/skills"
echo '{}' > "$d/.claude/settings.json"; echo '# a' > "$d/.claude/agents/reviewer.md"
echo '# c' > "$d/.claude/commands/ship.md"; echo '# s' > "$d/.claude/skills/deploy.md"
echo '{}' > "$d/.mcp.json"
git -C "$d" add -A; git -C "$d" commit -qm "chore: agent configuration"
check "settings, agents, commands, skills and .mcp.json are source" 0 "$d"

# Both of these are real fleet content, and both would fall to a lazier rule:
# routing-table.jsonl to "a .jsonl under an agent directory is a log" (tracked
# in 4 repos), .gitkeep to matching `sessions/` (tracked in 14).
d=$(mkrepo); mkdir -p "$d/.claude/agents" "$d/.claude/sessions"
echo '{"a":1}' > "$d/.claude/agents/routing-table.jsonl"
: > "$d/.claude/sessions/.gitkeep"
git -C "$d" add -A; git -C "$d" commit -qm "chore: authored jsonl and an empty session dir"
check "an authored .jsonl and a sessions placeholder are kept" 0 "$d"

d=$(mkrepo); mkdir -p "$d/.cursor/rules"
echo 'be nice' > "$d/.cursorrules"; echo '---' > "$d/.cursor/rules/style.mdc"
echo 'model: gpt' > "$d/.aider.conf.yml"; echo '{}' > "$d/.roomodes"
git -C "$d" add -A; git -C "$d" commit -qm "chore: other tools' configuration"
check "every other tool's configuration is kept too" 0 "$d"

d=$(mkrepo); echo '# instructions' > "$d/CLAUDE.md"; echo '# agents' > "$d/AGENTS.md"
mkdir -p "$d/.vscode" "$d/.idea" "$d/.devcontainer"
echo '{}' > "$d/.vscode/settings.json"; echo '<x/>' > "$d/.idea/workspace.xml"
echo '{}' > "$d/.devcontainer/devcontainer.json"
git -C "$d" add -A; git -C "$d" commit -qm "docs: instructions and editor config"
check "documentation and editor config are untouched" 0 "$d"

echo "== agent artefacts: the exhaust (expect 1) =="
d=$(mkrepo); mkdir -p "$d/.claude/logs"; echo '{"e":1}' > "$d/.claude/logs/session.jsonl"
git -C "$d" add -A; git -C "$d" commit -qm "chore: a session log"
check "a session log is refused" 1 "$d"

d=$(mkrepo); mkdir -p "$d/.claude/plans"; echo '# plan' > "$d/.claude/plans/thing.md"
git -C "$d" add -A; git -C "$d" commit -qm "chore: a plan file"
check "a plan file is refused" 1 "$d"

# One developer's permissions, imposed on everybody who clones.
d=$(mkrepo); mkdir -p "$d/.claude"; echo '{}' > "$d/.claude/settings.local.json"
git -C "$d" add -A; git -C "$d" commit -qm "chore: local overrides"
check "a personal settings.local.json is refused" 1 "$d"

d=$(mkrepo); mkdir -p "$d/.claude"; : > "$d/.claude/scheduled_tasks.lock"
echo '{}' > "$d/.claude/history.jsonl"
git -C "$d" add -A; git -C "$d" commit -qm "chore: a lock and a history"
check "a lock file and history.jsonl are refused" 1 "$d"

# The worst thing a `.claude/` can carry, and the one the secrets check cannot
# save you from: it reads only the lines a push ADDS, so a credentials file
# committed once is never looked at again.
d=$(mkrepo); mkdir -p "$d/.claude"; echo '{"t":"x"}' > "$d/.claude/.credentials.json"
git -C "$d" add -A; git -C "$d" commit -qm "chore: oauth token store"
check "a committed credentials file is refused" 1 "$d"

d=$(mkrepo); mkdir -p "$d/.claude"
echo '{}' > "$d/.claude/policy-limits.json"; echo '{}' > "$d/.claude/remote-settings.json"
git -C "$d" add -A; git -C "$d" commit -qm "chore: machine state"
check "server-pushed machine state is refused" 1 "$d"

d=$(mkrepo); echo 'chat' > "$d/.aider.chat.history.md"
git -C "$d" add -A; git -C "$d" commit -qm "chore: aider transcript"
check "aider's transcript is refused while its conf is not" 1 "$d"

d=$(mkrepo); mkdir -p "$d/.specstory/history"; echo 'chat' > "$d/.specstory/history/2026-01-01.md"
git -C "$d" add -A; git -C "$d" commit -qm "chore: recorded chat"
check "a recorded chat transcript is refused" 1 "$d"

d=$(mkrepo); mkdir -p "$d/.continue/sessions" "$d/.goose/logs"
echo '{}' > "$d/.continue/sessions/a.json"; echo 'x' > "$d/.goose/logs/a.log"
git -C "$d" add -A; git -C "$d" commit -qm "chore: other tools' exhaust"
check "other tools' session and log directories are refused" 1 "$d"

# The devcontainer image carries a whole .claude/ tree; a log dropped inside it
# is still a log, and nothing is spared for sitting under .devcontainer/.
d=$(mkrepo); mkdir -p "$d/.devcontainer/images/.claude/logs" "$d/.devcontainer/images/.claude/agents"
echo '# a' > "$d/.devcontainer/images/.claude/agents/x.md"
echo '{}' > "$d/.devcontainer/images/.claude/logs/session.jsonl"
git -C "$d" add -A; git -C "$d" commit -qm "chore: image payload with a stray log"
check "a log nested in the devcontainer payload is still refused" 1 "$d"

echo "== agent artefacts: scope, exemptions and reporting =="
# The tree, not the range: the artefact arrives in an ancestor and the change
# that added it is long merged. A range-scoped check would call this clean.
d=$(mkrepo); mkdir -p "$d/.claude/logs"; echo '{}' > "$d/.claude/logs/a.jsonl"
git -C "$d" add -A; git -C "$d" commit -qm "chore: a session log"
commit_msg "$d" "feat: unrelated later work"
check "an artefact merged earlier still fails a later clean change" 1 "$d" PC_HISTORY=range

d=$(mkrepo); mkdir -p "$d/.claude/logs"; echo '{}' > "$d/.claude/logs/a.jsonl"
git -C "$d" add -A; git -C "$d" commit -qm "chore: a session log"
git -C "$d" rm -qr .claude/logs; git -C "$d" commit -qm "chore: untrack the logs"
check "removing it in one commit clears the check" 0 "$d"

d=$(mkrepo); mkdir -p "$d/.claude/logs"; echo '{}' > "$d/.claude/logs/a.jsonl"
git -C "$d" add -A; git -C "$d" commit -qm "chore: a session log"
check "the check is switchable" 0 "$d" PC_AGENT_FILES=false

d=$(mkrepo); mkdir -p "$d/.claude/logs"; echo '{}' > "$d/.claude/logs/a.jsonl"
git -C "$d" add -A; git -C "$d" commit -qm "chore: a session log"
check "a bare allow entry exempts the whole subtree" 0 "$d" PC_AGENT_ALLOW=.claude/logs

# `.claude/logs/*` must cover hidden files too. An unquoted expansion would
# glob it against the working tree first, and filename globbing skips leading
# dots — so this passed for a.jsonl and quietly failed for .hidden.jsonl.
d=$(mkrepo); mkdir -p "$d/.claude/logs"
echo '{}' > "$d/.claude/logs/a.jsonl"; echo '{}' > "$d/.claude/logs/.hidden.jsonl"
git -C "$d" add -A; git -C "$d" commit -qm "chore: logs including a hidden one"
check "a glob allow entry covers hidden files too" 0 "$d" PC_AGENT_ALLOW=".claude/logs/*"

d=$(mkrepo); mkdir -p "$d/.claude/logs" "$d/.claude/plans"
echo '{}' > "$d/.claude/logs/a.jsonl"; echo '#' > "$d/.claude/plans/p.md"
git -C "$d" add -A; git -C "$d" commit -qm "chore: logs and plans"
check "an allow entry exempts only what it names" 1 "$d" PC_AGENT_ALLOW=".claude/logs/*"

# git C-quotes a path holding a non-ASCII or control character unless asked for
# NUL-delimited output, and the quote it adds lands exactly where `(^|/)` and
# `$` need a path boundary. Before that fix these were reported clean.
d=$(mkrepo); mkdir -p "$d/.claude/logs"; echo '{}' > "$d/.claude/logs/naïve.jsonl"
git -C "$d" add -A; git -C "$d" commit -qm "chore: accented log name"
check "a non-ASCII file name does not evade the scan" 1 "$d"

d=$(mkrepo); mkdir -p "$d/déjà/.claude"; echo '{}' > "$d/déjà/.claude/settings.local.json"
git -C "$d" add -A; git -C "$d" commit -qm "chore: anchored artefact below a non-ASCII parent"
check "an end-anchored pattern still matches below a non-ASCII parent" 1 "$d"

d=$(mkrepo); mkdir -p "$d/.claude/logs"; echo '{}' > "$d/.claude/logs/$(printf 'two\nlines').jsonl"
git -C "$d" add -A; git -C "$d" commit -qm "chore: newline in the file name"
check "a newline in the file name does not split a record" 1 "$d"

# A tracked path is attacker-controlled input and ends up as an associative
# array subscript, a [[ ]] operand and an annotation. `declare -A` is what makes
# the subscript a string rather than an arithmetic expression; this is here so
# that dropping the -A, or reaching for an indexed array, fails loudly.
d=$(mkrepo); mkdir -p "$d/a\$(touch PWNED).d/.claude" "$d/c];touch PWNED3;x[.d/.claude"
printf 'x' > "$d/a\$(touch PWNED).d/.claude/settings.local.json"
printf 'x' > "$d/c];touch PWNED3;x[.d/.claude/settings.local.json"
git -C "$d" add -A; git -C "$d" commit -qm "chore: hostile parent names"
( cd "$d" && env GITHUB_STEP_SUMMARY=/dev/null bash "$GATE" HEAD HEAD~1..HEAD ) >/dev/null 2>&1
rc=$?
# The exit status belongs in the assertion: "nothing was executed" is also true
# of a scan that matched nothing, so without it a regression in the matching
# would leave this test green while proving only that a clean run is harmless.
if [ "$rc" -eq 1 ] && [ ! -e "$d/PWNED" ] && [ ! -e "$d/PWNED3" ]; then
    PASS=$((PASS+1)); printf '  ok   %s\n' "a hostile file name is data, never evaluated"
elif [ "$rc" -ne 1 ]; then
    FAIL=$((FAIL+1)); printf '  FAIL %s — the gate did not refuse them (exit %s)\n' "a hostile file name is data, never evaluated" "$rc"
else
    FAIL=$((FAIL+1)); printf '  FAIL %s — the scan executed part of a path\n' "a hostile file name is data, never evaluated"
fi
rm -rf "$d"

# The root is found with the pattern list, so the pattern list has to reach the
# matcher intact. With the escape stripped, `\.` becomes a bare `.`, `aclaude/`
# matches `(^|/).claude/logs/`, and the verdict names an ordinary directory.
d=$(mkrepo); mkdir -p "$d/aclaude/.claude/logs"
echo '{}' > "$d/aclaude/.claude/logs/a.jsonl"
git -C "$d" add -A; git -C "$d" commit -qm "chore: log below a lookalike"
r="$(mktemp)"
( cd "$d" && env GITHUB_STEP_SUMMARY=/dev/null PC_REPORT="$r" bash "$GATE" HEAD HEAD~1..HEAD ) >/dev/null 2>&1
if grep -qF '`aclaude/.claude/logs/`' "$r" && ! grep -qF '`aclaude/`' "$r"; then
    PASS=$((PASS+1)); printf '  ok   %s\n' "a directory whose name merely ends in the pattern is not the root"
else
    FAIL=$((FAIL+1)); printf '  FAIL %s\n%s\n' "a directory whose name merely ends in the pattern is not the root" "$(sed 's/^/       /' "$r")"
fi
rm -rf "$d" "$r"

# The verdict names the artefact root, and getting that root wrong is worse
# than not collapsing at all: the surrounding `.claude/` is legitimate here, so
# naming it as the thing to delete would point at the agent's own source.
d=$(mkrepo); mkdir -p "$d/.claude/logs" "$d/.claude/agents"
echo '# a' > "$d/.claude/agents/x.md"
for i in 1 2 3; do echo '{}' > "$d/.claude/logs/a$i.jsonl"; done
git -C "$d" add -A; git -C "$d" commit -qm "chore: agent source beside its logs"
r="$(mktemp)"
( cd "$d" && env GITHUB_STEP_SUMMARY=/dev/null PC_REPORT="$r" bash "$GATE" HEAD HEAD~1..HEAD ) >/dev/null 2>&1
if grep -qF '`.claude/logs/` — 3 file(s)' "$r" && ! grep -qF '`.claude/`' "$r"; then
    PASS=$((PASS+1)); printf '  ok   %s\n' "the reported root is the log directory, not the .claude around it"
else
    FAIL=$((FAIL+1)); printf '  FAIL %s\n%s\n' "the reported root is the log directory, not the .claude around it" "$(sed 's/^/       /' "$r")"
fi
rm -rf "$d" "$r"

# The whole-repository scope (push, manual runs) is not a tree-ish; the check
# has to fall back to the checked-out head rather than fail the job.
d=$(mkrepo); mkdir -p "$d/.claude/logs"; echo '{}' > "$d/.claude/logs/a.jsonl"
git -C "$d" add -A; git -C "$d" commit -qm "chore: a session log"
out="$(cd "$d" && env GITHUB_STEP_SUMMARY=/dev/null bash "$GATE" --branches 2>&1)"; rc=$?
if [ "$rc" -eq 1 ] && printf '%s' "$out" | grep -q 'agent artefact'; then
    PASS=$((PASS+1)); printf '  ok   %s\n' "--branches scans the checked-out tree"
else
    FAIL=$((FAIL+1)); printf '  FAIL %s (want exit 1 and an artefact error, got %s)\n' "--branches scans the checked-out tree" "$rc"
fi
rm -rf "$d"

# rewrite-history.sh keeps the artefact check off on both of its gate calls: it
# rewrites messages and identities and never touches the tree, so a tracked log
# would make --execute refuse to push a correct rewrite. Running the script
# itself needs a network mirror and git-filter-repo; what is guarded here is the
# pairing that can silently come undone.
#
# Counted on the invoking lines themselves, not on the file: the comment that
# explains the pairing names the variable too, and matching that would make the
# guard pass on the explanation alone. Two, not "at least one": the before scan
# feeds the counters the report prints, the after scan is what --execute reads.
calls="$(grep -c 'post-commit.sh" --branches' "$ROOT/scripts/rewrite-history.sh")"
guarded="$(grep 'post-commit.sh" --branches' "$ROOT/scripts/rewrite-history.sh" | grep -c 'PC_AGENT_FILES=false')"
if [ "$calls" -eq 2 ] && [ "$guarded" -eq 2 ]; then
    PASS=$((PASS+1)); printf '  ok   %s\n' "every rewrite-history gate call disables the artefact check"
else
    FAIL=$((FAIL+1)); printf '  FAIL %s (want 2 call(s) all guarded, got %s call(s), %s guarded)\n' "every rewrite-history gate call disables the artefact check" "$calls" "$guarded"
fi


echo "== usage errors (expect 2) =="
d=$(mkrepo)
out="$(cd "$d" && bash "$GATE" 2>&1)"; rc=$?
if [ "$rc" -eq 2 ]; then PASS=$((PASS+1)); echo "  ok   no head-rev is a usage error"; else FAIL=$((FAIL+1)); echo "  FAIL usage (got $rc)"; fi
rm -rf "$d"

echo ""
echo "passed: $PASS  failed: $FAIL"
[ "$FAIL" -eq 0 ]
