#!/usr/bin/env bash
# ============================================================================
# rewrite-history.sh — scrub AI attribution from a repository's ENTIRE history.
#
# DRY-RUN BY DEFAULT. Clones a mirror into a temp dir, rewrites it there,
# runs the gate over the result and prints what changed. Nothing reaches
# GitHub until --execute, which force-pushes every branch and tag of the
# rewritten mirror. That step changes every commit SHA after the first
# tainted one, breaks every open PR and every existing clone, and cannot be
# undone once pushed — run it per repository, deliberately.
#
# Rewrites:
#   · message lines that ARE an attribution: trailers naming an assistant,
#     "Generated by/with …" banners, 🤖 lines, "AI-assisted" markers, "Plan:"
#     footers. A subject line is scrubbed of 🤖 / "(AI-assisted)" fragments
#     but never deleted — an empty subject is worse than a tainted one; a
#     subject that still matches is listed for a human to reword.
#   · author/committer identities outside --authors → --identity (default: the
#     authenticated gh user's name and primary email). --remap overrides that
#     per address, so a co-contributor's commits keep their own account
#     instead of being folded onto the default identity: the gate only ever
#     accepted GitHub noreply addresses, so a personal address still has to
#     move — but it moves to that person's own noreply, not to someone else's.
# Never touches file contents, dates, or ordinary prose. Vendor mentions
# left in ordinary prose are listed at the end for a manual decision.
# Known cost: git-filter-repo drops GPG signatures, so every signed commit
# from the first rewritten one onward loses its signature.
#
# usage: rewrite-history.sh owner/repo [--execute] [--identity "Name <email>"]
#                                      [--authors "login[,login]"]
#                                      [--keep DIR]   (keep the mirror for inspection)
# needs: git-filter-repo, gh, python3.
# ============================================================================
set -uo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO="${1:-}"; shift || true
EXECUTE=false; IDENTITY=""; KEEP=""; AUTHORS=""; REMAP=()
while [ $# -gt 0 ]; do
    case "$1" in
        --execute) EXECUTE=true ;;
        --identity) IDENTITY="$2"; shift ;;
        --authors) AUTHORS="$2"; shift ;;
        --remap) REMAP+=("$2"); shift ;;
        --keep) KEEP="$2"; shift ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac; shift
done
[ -n "$REPO" ] || { echo "usage: rewrite-history.sh owner/repo [--execute] [--identity 'Name <email>'] [--authors 'login[,login]'] [--remap 'old@email=Name <new@email>'] [--keep DIR]" >&2; exit 2; }
command -v git-filter-repo >/dev/null || { echo "git-filter-repo is required (apt install git-filter-repo)" >&2; exit 2; }

# The replacement identity is the account's GitHub noreply address, never its
# primary email: a private address is exactly what the identity gate refuses,
# so mapping onto one would leave the history failing after the rewrite.
LOGIN="$(gh api user --jq .login)"
UID_NUM="$(gh api user --jq .id)"
[ -n "$AUTHORS" ] || AUTHORS="$LOGIN"
if [ -z "$IDENTITY" ]; then
    NAME="$(gh api user --jq '.name // .login')"
    IDENTITY="$NAME <${UID_NUM}+${LOGIN}@users.noreply.github.com>"
fi

WORK="${KEEP:-$(mktemp -d)}"
MIRROR="$WORK/mirror"
[ -n "$KEEP" ] || trap 'rm -rf "$WORK"' EXIT
echo "▸ $REPO — mirror clone into $MIRROR"
git clone --mirror -q "https://github.com/$REPO.git" "$MIRROR" || exit 1

# --branches, not --all: a mirror also carries GitHub's refs/pull/*, which are
# never pushed back and would inflate every count with closed-PR commits.
BEFORE_COUNT="$(git -C "$MIRROR" rev-list --branches --tags --count)"
# The gate exits 1 on a tainted history — expected here — and `pipefail`
# would turn that into a pipeline failure, so capture first, parse after.
BEFORE_OUT="$(cd "$MIRROR" && GITHUB_STEP_SUMMARY=/dev/null PC_MAX_REPORT=0 PC_AUTHORS="$AUTHORS" bash "$SCRIPT_DIR/post-commit.sh" --branches 2>&1 || true)"
BEFORE_TAINT="$(printf '%s' "$BEFORE_OUT" | grep -oE '^::error::[0-9]+ tainted' | grep -oE '[0-9]+' || true)"
: "${BEFORE_TAINT:=0}"
# Identity violations are counted separately: a repository can be free of AI
# attribution and still carry a personal address on every commit, which is
# just as much a reason to rewrite.
BEFORE_IDENT="$(printf '%s' "$BEFORE_OUT" | grep -oE '^::error::[0-9]+ commit\(s\) not authored' | grep -oE '[0-9]+' || true)"
: "${BEFORE_IDENT:=0}"
# And trailers separately again: a history can carry an allowed author on every
# commit and still name a personal address in a Co-authored-by line.
BEFORE_TRAIL="$(printf '%s' "$BEFORE_OUT" | grep -oE '^::error::[0-9]+ commit\(s\) carry a trailer' | grep -oE '[0-9]+' || true)"
: "${BEFORE_TRAIL:=0}"

if [ "$BEFORE_TAINT" -eq 0 ] && [ "$BEFORE_IDENT" -eq 0 ] && [ "$BEFORE_TRAIL" -eq 0 ]; then
    echo "  $REPO: history already clean on every branch — nothing to rewrite."
    exit 0
fi

# --- identities -------------------------------------------------------------
# Everything that is not one of the allowed accounts is remapped, not just the
# AI agents: a personal address on a commit is the same leak as an assistant's
# trailer and the gate's identity check refuses both. The two families the
# gate accepts on top of the list are left alone here for the same reason it
# accepts them — GitHub's merge committer and app accounts cannot be
# re-authored as a human.
ALLOWED_RE=""
for login in ${AUTHORS//,/ }; do
    esc="$(printf '%s' "$login" | sed 's/[][\\.^$*+?(){}|]/\\&/g')"
    ALLOWED_RE="${ALLOWED_RE}|<([0-9]+\+)?${esc}@users\.noreply\.github\.com>$"
done
ALLOWED_RE="${ALLOWED_RE#|}"
ALLOWED_RE="${ALLOWED_RE}|<noreply@github\.com>$|<[0-9]+\+[^@]+\[bot\]@users\.noreply\.github\.com>$"

# The same allow-list, as a bare email regex: the message callback needs it to
# decide whether a Co-authored-by / Signed-off-by trailer may stay. Written to
# a file rather than interpolated, so no quoting of the regex survives into
# Python source.
ALLOWED_EMAIL_RE=""
for login in ${AUTHORS//,/ }; do
    esc="$(printf '%s' "$login" | sed 's/[][\\.^$*+?(){}|]/\\&/g')"
    ALLOWED_EMAIL_RE="${ALLOWED_EMAIL_RE}|^([0-9]+\+)?${esc}@users\.noreply\.github\.com$"
done
ALLOWED_EMAIL_RE="${ALLOWED_EMAIL_RE#|}"
ALLOWED_EMAIL_RE="${ALLOWED_EMAIL_RE}|^noreply@github\.com$|^[0-9]+\+[^@]+\[bot\]@users\.noreply\.github\.com$"
for entry in ${REMAP[@]+"${REMAP[@]}"}; do
    tgt="${entry#*=}"; tgt="${tgt##*<}"; tgt="${tgt%>}"
    esc="$(printf '%s' "$tgt" | sed 's/[][\\.^$*+?(){}|]/\\&/g')"
    ALLOWED_EMAIL_RE="${ALLOWED_EMAIL_RE}|^${esc}$"
done
ALLOWED_RE_FILE="$WORK/allowed.re"
printf '%s' "$ALLOWED_EMAIL_RE" > "$ALLOWED_RE_FILE"

MAILMAP="$WORK/mailmap"
: > "$MAILMAP"

# --remap entries are written first and then held out of the catch-all below,
# so an address named here lands on the identity it was given and never on
# $IDENTITY. Anything not named still falls through to the catch-all.
REMAP_RE=""
for entry in ${REMAP[@]+"${REMAP[@]}"}; do
    old_addr="${entry%%=*}"; new_id="${entry#*=}"
    [ "$old_addr" != "$entry" ] && [ -n "$new_id" ] || {
        echo "--remap takes old@email=Name <new@email>, got: $entry" >&2; exit 2; }
    printf '%s <%s>\n' "$new_id" "$old_addr" >> "$MAILMAP"
    esc="$(printf '%s' "$old_addr" | sed 's/[][\\.^$*+?(){}|]/\\&/g')"
    REMAP_RE="${REMAP_RE}|<${esc}>\$"
done
REMAP_RE="${REMAP_RE#|}"

# --branches --tags, not --branches: a tag can hold commits no branch reaches,
# and an identity that only appears there would survive the rewrite untouched.
git -C "$MIRROR" log --branches --tags --format='%an <%ae>%n%cn <%ce>' | sort -u \
    | grep -viE -- "$ALLOWED_RE" \
    | { [ -n "$REMAP_RE" ] && grep -viE -- "$REMAP_RE" || cat; } \
    | while IFS= read -r id; do printf '%s %s\n' "$IDENTITY" "$id"; done >> "$MAILMAP"
ID_COUNT="$(wc -l < "$MAILMAP" | tr -d ' ')"

# --- messages ----------------------------------------------------------------
CALLBACK="$WORK/callback.py"
cat > "$CALLBACK" <<'PY'
import re
ATTR = re.compile(
    rb'(?i)(^\s*(co-authored-by|assisted-by|generated-by|authored-by|committed-by|reviewed-by|signed-off-by)\s*:.*'
    rb'(claude|anthropic|openai|chatgpt|gpt-[0-9]|copilot|gemini|codeium|cursor|devin|aider|llm|[^a-z]ai[^a-z]))'
    rb'|noreply@anthropic\.com|copilot@users\.noreply\.github\.com'
    rb'|generated\s+(by|with|using)\s+\[?(claude|ai|gpt|chatgpt|anthropic|copilot|gemini|cursor|devin|aider|an?\s+llm)'
    rb'|\bai[-\s]?(assisted|generated|authored|written)\b'
    rb'|\b(written|authored|generated)\s+by\s+an?\s+(ai|llm|language\s+model)\b'
    rb'|^\s*plan:\s')
ROBOT = '🤖'.encode()

# An identity trailer carries an address as durably as the author field, so
# the same allow-list decides it. A trailer naming an account that is not
# allowed is dropped whole: rewriting it to someone else would invent a
# co-author, and keeping it leaves the address in the history for good.
TRAILER = re.compile(
    rb'(?i)^\s*(co-authored-by|signed-off-by|authored-by|committed-by'
    rb'|assisted-by|reviewed-by|acked-by|tested-by|reported-by|suggested-by)\s*:')
EMAIL = re.compile(rb'<([^>]*)>')
with open('__ALLOWED_RE_PATH__', 'rb') as fh:
    ALLOWED = re.compile(fh.read().strip(), re.I)

def foreign_trailer(l):
    if not TRAILER.match(l):
        return False
    body = l.split(b':', 1)[1]
    name = body.split(b'<')[0].strip()
    if name.lower().endswith(b'[bot]'):
        return False
    m = EMAIL.search(l)
    if not m:
        return True
    return not ALLOWED.search(m.group(1).strip())

lines = message.split(b'\n')
# Strict no-op on a clean message: whitespace normalisation alone must not
# rewrite a commit, or every untainted commit gets a new SHA for nothing.
if not any(ATTR.search(l) or ROBOT in l or foreign_trailer(l) for l in lines):
    return message
subject = lines[0].replace(ROBOT, b'')
subject = re.sub(rb'(?i)\s*[\(\[]?\bai[-\s]?assisted[\)\]]?', b'', subject).rstrip()
body = [l for l in lines[1:] if not (ATTR.search(l) or ROBOT in l or foreign_trailer(l))]
while body and not body[-1].strip():
    body.pop()
out = []
for l in body:
    if not l.strip() and out and not out[-1].strip():
        continue
    out.append(l)
while out and not out[0].strip():
    out.pop(0)
return subject + (b'\n\n' + b'\n'.join(out) if out else b'') + b'\n'
PY

sed -i "s|__ALLOWED_RE_PATH__|$ALLOWED_RE_FILE|" "$CALLBACK"

echo "▸ rewriting messages and identities ($ID_COUNT foreign identit$([ "$ID_COUNT" = 1 ] && echo y || echo ies) → $IDENTITY)"
( cd "$MIRROR" && git filter-repo --quiet --force --mailmap "$MAILMAP" \
      --message-callback "$(cat "$CALLBACK")" ) >"$WORK/filter-repo.log" 2>&1 \
    || { echo "filter-repo failed:" >&2; cat "$WORK/filter-repo.log" >&2; exit 1; }

AFTER_COUNT="$(git -C "$MIRROR" rev-list --branches --tags --count)"
# commit-map has a header line ("old new"); skip it.
CHANGED="$(awk 'NR>1 && $1!=$2' "$MIRROR/filter-repo/commit-map" 2>/dev/null | wc -l | tr -d ' ')"

# --- verify with the gate itself --------------------------------------------
GATE_OUT="$(cd "$MIRROR" && GITHUB_STEP_SUMMARY=/dev/null PC_MAX_REPORT=20 PC_AUTHORS="$AUTHORS" bash "$SCRIPT_DIR/post-commit.sh" --branches 2>&1)"
GATE_RC=$?
RESIDUAL_KW="$(git -C "$MIRROR" log --branches --format='%h %s%n%b' | grep -iE 'claude|anthropic|copilot|chatgpt|openai|gemini|\bllm\b' | head -20)"
OPEN_PRS="$(gh pr list --repo "$REPO" --state open --json number,title --jq '.[] | "#\(.number) \(.title)"' 2>/dev/null)"

echo ""
echo "════════════════════════════════════════════════════════════"
echo "  $REPO"
echo "════════════════════════════════════════════════════════════"
echo "  commits          : $BEFORE_COUNT → $AFTER_COUNT (count unchanged by design)"
echo "  tainted before   : $BEFORE_TAINT"
echo "  foreign identity : $BEFORE_IDENT commit(s)"
echo "  foreign trailers : $BEFORE_TRAIL commit(s)"
echo "  commits rewritten: $CHANGED (new SHA)"
echo "  identities mapped: $ID_COUNT"
[ "$ID_COUNT" -gt 0 ] && sed 's/^/      /' "$MAILMAP"
if [ "$GATE_RC" -eq 0 ]; then
    echo "  gate after       : ✅ clean"
else
    echo "  gate after       : ❌ still failing — subjects a human must reword:"
    printf '%s\n' "$GATE_OUT" | grep '^::error::AI attribution' | sed 's/^::error::/      /' | head -20
fi
if [ -n "$RESIDUAL_KW" ]; then
    echo "  vendor mentions left in ordinary prose (manual decision):"
    printf '%s\n' "$RESIDUAL_KW" | sed 's/^/      /'
fi
if [ -n "$OPEN_PRS" ]; then
    echo "  open PRs (same-repo branches are rewritten and pushed along with main; fork-based ones break):"
    printf '%s\n' "$OPEN_PRS" | sed 's/^/      /'
fi
echo ""

if ! $EXECUTE; then
    echo "  DRY RUN — nothing pushed. Re-run with --execute to force-push the rewrite."
    exit 0
fi
if [ "$GATE_RC" -ne 0 ]; then
    echo "  refusing to push a history the gate still rejects" >&2
    exit 1
fi
echo "▸ force-pushing branches and tags to $REPO"
git -C "$MIRROR" remote add origin "https://github.com/$REPO.git" 2>/dev/null || git -C "$MIRROR" remote set-url origin "https://github.com/$REPO.git"
# Explicit refspecs, not --mirror: a mirror clone also carries refs/pull/*,
# which GitHub refuses to update and which would clutter the push with
# rejections.
git -C "$MIRROR" push --force origin 'refs/heads/*:refs/heads/*' 'refs/tags/*:refs/tags/*' || exit 1
echo "▸ done — every clone of $REPO must now be re-cloned (not pulled)."
