#!/usr/bin/env bash
# ============================================================================
# rewrite-history.sh — scrub AI attribution from a repository's ENTIRE history.
#
# DRY-RUN BY DEFAULT. Clones a mirror into a temp dir, rewrites it there,
# runs the gate over the result and prints what changed. Nothing reaches
# GitHub until --execute, which force-pushes every branch and tag of the
# rewritten mirror. That step changes every commit SHA after the first
# tainted one, breaks every open PR and every existing clone, and cannot be
# undone once pushed — run it per repository, deliberately.
#
# Rewrites:
#   · message lines that ARE an attribution: trailers naming an assistant,
#     "Generated by/with …" banners, 🤖 lines, "AI-assisted" markers, "Plan:"
#     footers. A subject line is scrubbed of 🤖 / "(AI-assisted)" fragments
#     but never deleted — an empty subject is worse than a tainted one; a
#     subject that still matches is listed for a human to reword.
#   · author/committer identities of AI agents → --identity (default: the
#     authenticated gh user's name and primary email).
# Never touches file contents, dates, or ordinary prose. Vendor mentions
# left in ordinary prose are listed at the end for a manual decision.
#
# usage: rewrite-history.sh owner/repo [--execute] [--identity "Name <email>"]
#                                      [--keep DIR]   (keep the mirror for inspection)
# needs: git-filter-repo, gh, python3.
# ============================================================================
set -uo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO="${1:-}"; shift || true
EXECUTE=false; IDENTITY=""; KEEP=""
while [ $# -gt 0 ]; do
    case "$1" in
        --execute) EXECUTE=true ;;
        --identity) IDENTITY="$2"; shift ;;
        --keep) KEEP="$2"; shift ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac; shift
done
[ -n "$REPO" ] || { echo "usage: rewrite-history.sh owner/repo [--execute] [--identity 'Name <email>'] [--keep DIR]" >&2; exit 2; }
command -v git-filter-repo >/dev/null || { echo "git-filter-repo is required (apt install git-filter-repo)" >&2; exit 2; }

if [ -z "$IDENTITY" ]; then
    NAME="$(gh api user --jq '.name // .login')"
    EMAIL="$(gh api user/emails --jq '.[] | select(.primary) | .email' 2>/dev/null || true)"
    [ -n "$EMAIL" ] || EMAIL="$(git config --global user.email || true)"
    [ -n "$EMAIL" ] || { echo "cannot determine an email for --identity; pass it explicitly" >&2; exit 2; }
    IDENTITY="$NAME <$EMAIL>"
fi

WORK="${KEEP:-$(mktemp -d)}"
MIRROR="$WORK/mirror"
[ -n "$KEEP" ] || trap 'rm -rf "$WORK"' EXIT
echo "▸ $REPO — mirror clone into $MIRROR"
git clone --mirror -q "https://github.com/$REPO.git" "$MIRROR" || exit 1

BEFORE_COUNT="$(git -C "$MIRROR" rev-list --all --count)"
BEFORE_TAINT="$(cd "$MIRROR" && GITHUB_STEP_SUMMARY=/dev/null PC_MAX_REPORT=0 bash "$SCRIPT_DIR/post-commit.sh" --all 2>&1 | grep -oE '^::error::[0-9]+ tainted' | grep -oE '[0-9]+' || echo 0)"

# --- identities: every author/committer that looks like an AI agent --------
AI_ID='claude|anthropic|copilot|openai|chatgpt|gemini|devin|aider|cursor|codeium|\bai\b|\bllm\b'
MAILMAP="$WORK/mailmap"
git -C "$MIRROR" log --all --format='%an <%ae>%n%cn <%ce>' | sort -u | grep -iE -- "$AI_ID" \
    | while IFS= read -r id; do printf '%s %s\n' "$IDENTITY" "$id"; done > "$MAILMAP"
ID_COUNT="$(wc -l < "$MAILMAP" | tr -d ' ')"

# --- messages ----------------------------------------------------------------
CALLBACK="$WORK/callback.py"
cat > "$CALLBACK" <<'PY'
import re
ATTR = re.compile(
    rb'(?i)(^\s*(co-authored-by|assisted-by|generated-by|authored-by|committed-by|reviewed-by|signed-off-by)\s*:.*'
    rb'(claude|anthropic|openai|chatgpt|gpt-[0-9]|copilot|gemini|codeium|cursor|devin|aider|llm|[^a-z]ai[^a-z]))'
    rb'|noreply@anthropic\.com|copilot@users\.noreply\.github\.com'
    rb'|generated\s+(by|with|using)\s+\[?(claude|ai|gpt|chatgpt|anthropic|copilot|gemini|cursor|devin|aider|an?\s+llm)'
    rb'|\bai[-\s]?(assisted|generated|authored|written)\b'
    rb'|\b(written|authored|generated)\s+by\s+an?\s+(ai|llm|language\s+model)\b'
    rb'|^\s*plan:\s')
ROBOT = '🤖'.encode()
lines = message.split(b'\n')
subject = lines[0].replace(ROBOT, b'')
subject = re.sub(rb'(?i)\s*[\(\[]?\bai[-\s]?assisted[\)\]]?', b'', subject).rstrip()
body = [l for l in lines[1:] if not (ATTR.search(l) or ROBOT in l)]
while body and not body[-1].strip():
    body.pop()
out = []
for l in body:
    if not l.strip() and out and not out[-1].strip():
        continue
    out.append(l)
while out and not out[0].strip():
    out.pop(0)
return subject + (b'\n\n' + b'\n'.join(out) if out else b'') + b'\n'
PY

echo "▸ rewriting messages and identities ($ID_COUNT AI identit$([ "$ID_COUNT" = 1 ] && echo y || echo ies) → $IDENTITY)"
( cd "$MIRROR" && git filter-repo --quiet --force --mailmap "$MAILMAP" \
      --message-callback "$(cat "$CALLBACK")" ) || { echo "filter-repo failed" >&2; exit 1; }

AFTER_COUNT="$(git -C "$MIRROR" rev-list --all --count)"
CHANGED="$(awk '$1!=$2' "$MIRROR/filter-repo/commit-map" 2>/dev/null | wc -l | tr -d ' ')"

# --- verify with the gate itself --------------------------------------------
GATE_OUT="$(cd "$MIRROR" && GITHUB_STEP_SUMMARY=/dev/null PC_MAX_REPORT=20 bash "$SCRIPT_DIR/post-commit.sh" --all 2>&1)"
GATE_RC=$?
RESIDUAL_KW="$(git -C "$MIRROR" log --all --format='%h %s%n%b' | grep -iE 'claude|anthropic|copilot|chatgpt|openai|gemini|\bllm\b' | head -20)"
OPEN_PRS="$(gh pr list --repo "$REPO" --state open --json number,title --jq '.[] | "#\(.number) \(.title)"' 2>/dev/null)"

echo ""
echo "════════════════════════════════════════════════════════════"
echo "  $REPO"
echo "════════════════════════════════════════════════════════════"
echo "  commits          : $BEFORE_COUNT → $AFTER_COUNT (count unchanged by design)"
echo "  tainted before   : $BEFORE_TAINT"
echo "  commits rewritten: $CHANGED (new SHA)"
echo "  identities mapped: $ID_COUNT"
[ "$ID_COUNT" -gt 0 ] && sed 's/^/      /' "$MAILMAP"
if [ "$GATE_RC" -eq 0 ]; then
    echo "  gate after       : ✅ clean"
else
    echo "  gate after       : ❌ still failing — subjects a human must reword:"
    printf '%s\n' "$GATE_OUT" | grep '^::error::AI attribution' | sed 's/^::error::/      /' | head -20
fi
if [ -n "$RESIDUAL_KW" ]; then
    echo "  vendor mentions left in ordinary prose (manual decision):"
    printf '%s\n' "$RESIDUAL_KW" | sed 's/^/      /'
fi
if [ -n "$OPEN_PRS" ]; then
    echo "  open PRs that will need a rebase after the push:"
    printf '%s\n' "$OPEN_PRS" | sed 's/^/      /'
fi
echo ""

if ! $EXECUTE; then
    echo "  DRY RUN — nothing pushed. Re-run with --execute to force-push the rewrite."
    exit 0
fi
if [ "$GATE_RC" -ne 0 ]; then
    echo "  refusing to push a history the gate still rejects" >&2
    exit 1
fi
echo "▸ force-pushing branches and tags to $REPO"
git -C "$MIRROR" remote add origin "https://github.com/$REPO.git" 2>/dev/null || git -C "$MIRROR" remote set-url origin "https://github.com/$REPO.git"
# Explicit refspecs, not --mirror: a mirror clone also carries refs/pull/*,
# which GitHub refuses to update and which would clutter the push with
# rejections.
git -C "$MIRROR" push --force origin 'refs/heads/*:refs/heads/*' 'refs/tags/*:refs/tags/*' || exit 1
echo "▸ done — every clone of $REPO must now be re-cloned (not pulled)."
